{
 "title": "Grafana First Dashborad Project",
 "description": "Basic Dashboard using Grafana and Prometheis",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": " CPU",
   "type": "timeseries",
   "description": "CPU utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "JVM memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "description": "Average response time of the requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"spring-actuator\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"spring-actuator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "Percentage of requests that resulted in errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"spring-actuator\", status=\"error\"}[1m])) / sum(rate(http_server_requests_seconds_count{job=\"spring-actuator\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": ":Number of requests per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"spring-actuator\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}